// Generated by gencpp from file rm_msgs/Arm_Current_Status.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ARM_CURRENT_STATUS_H
#define RM_MSGS_MESSAGE_ARM_CURRENT_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Arm_Current_Status_
{
  typedef Arm_Current_Status_<ContainerAllocator> Type;

  Arm_Current_Status_()
    : arm_current_status()  {
    }
  Arm_Current_Status_(const ContainerAllocator& _alloc)
    : arm_current_status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _arm_current_status_type;
  _arm_current_status_type arm_current_status;





  typedef boost::shared_ptr< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_Current_Status_

typedef ::rm_msgs::Arm_Current_Status_<std::allocator<void> > Arm_Current_Status;

typedef boost::shared_ptr< ::rm_msgs::Arm_Current_Status > Arm_Current_StatusPtr;
typedef boost::shared_ptr< ::rm_msgs::Arm_Current_Status const> Arm_Current_StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Arm_Current_Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Arm_Current_Status_<ContainerAllocator1> & lhs, const ::rm_msgs::Arm_Current_Status_<ContainerAllocator2> & rhs)
{
  return lhs.arm_current_status == rhs.arm_current_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Arm_Current_Status_<ContainerAllocator1> & lhs, const ::rm_msgs::Arm_Current_Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22014e450b07851d8586a5146c339be8";
  }

  static const char* value(const ::rm_msgs::Arm_Current_Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22014e450b07851dULL;
  static const uint64_t static_value2 = 0x8586a5146c339be8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Arm_Current_Status";
  }

  static const char* value(const ::rm_msgs::Arm_Current_Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string arm_current_status\n"
;
  }

  static const char* value(const ::rm_msgs::Arm_Current_Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_current_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_Current_Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Arm_Current_Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Arm_Current_Status_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "arm_current_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.arm_current_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_ARM_CURRENT_STATUS_H
