// Generated by gencpp from file rm_msgs/Arm_Current_State.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ARM_CURRENT_STATE_H
#define RM_MSGS_MESSAGE_ARM_CURRENT_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Arm_Current_State_
{
  typedef Arm_Current_State_<ContainerAllocator> Type;

  Arm_Current_State_()
    : joint()
    , Pose()
    , err()
    , dof(0)  {
      Pose.assign(0.0);
  }
  Arm_Current_State_(const ContainerAllocator& _alloc)
    : joint(_alloc)
    , Pose()
    , err(_alloc)
    , dof(0)  {
  (void)_alloc;
      Pose.assign(0.0);
  }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_type;
  _joint_type joint;

   typedef boost::array<float, 6>  _Pose_type;
  _Pose_type Pose;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _err_type;
  _err_type err;

   typedef uint8_t _dof_type;
  _dof_type dof;





  typedef boost::shared_ptr< ::rm_msgs::Arm_Current_State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Arm_Current_State_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_Current_State_

typedef ::rm_msgs::Arm_Current_State_<std::allocator<void> > Arm_Current_State;

typedef boost::shared_ptr< ::rm_msgs::Arm_Current_State > Arm_Current_StatePtr;
typedef boost::shared_ptr< ::rm_msgs::Arm_Current_State const> Arm_Current_StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Arm_Current_State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Arm_Current_State_<ContainerAllocator1> & lhs, const ::rm_msgs::Arm_Current_State_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint &&
    lhs.Pose == rhs.Pose &&
    lhs.err == rhs.err &&
    lhs.dof == rhs.dof;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Arm_Current_State_<ContainerAllocator1> & lhs, const ::rm_msgs::Arm_Current_State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Arm_Current_State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Arm_Current_State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Arm_Current_State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c96583b56d85a30b9b36f7638260f04";
  }

  static const char* value(const ::rm_msgs::Arm_Current_State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c96583b56d85a30ULL;
  static const uint64_t static_value2 = 0xb9b36f7638260f04ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Arm_Current_State";
  }

  static const char* value(const ::rm_msgs::Arm_Current_State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint\n"
"float32[6] Pose\n"
"uint16[] err\n"
"uint8 dof\n"
"\n"
;
  }

  static const char* value(const ::rm_msgs::Arm_Current_State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.Pose);
      stream.next(m.err);
      stream.next(m.dof);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_Current_State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Arm_Current_State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Arm_Current_State_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint: ";
    if (v.joint.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint[i]);
    }
    if (v.joint.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Pose: ";
    if (v.Pose.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.Pose.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.Pose[i]);
    }
    if (v.Pose.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "err: ";
    if (v.err.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.err.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.err[i]);
    }
    if (v.err.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dof: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dof);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_ARM_CURRENT_STATE_H
