// Generated by gencpp from file rm_msgs/CartePosCustom.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CARTEPOSCUSTOM_H
#define RM_MSGS_MESSAGE_CARTEPOSCUSTOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct CartePosCustom_
{
  typedef CartePosCustom_<ContainerAllocator> Type;

  CartePosCustom_()
    : Pose()
    , follow(false)
    , trajectory_mode(0)
    , radio(0)  {
    }
  CartePosCustom_(const ContainerAllocator& _alloc)
    : Pose(_alloc)
    , follow(false)
    , trajectory_mode(0)
    , radio(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _Pose_type;
  _Pose_type Pose;

   typedef uint8_t _follow_type;
  _follow_type follow;

   typedef uint8_t _trajectory_mode_type;
  _trajectory_mode_type trajectory_mode;

   typedef uint8_t _radio_type;
  _radio_type radio;





  typedef boost::shared_ptr< ::rm_msgs::CartePosCustom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::CartePosCustom_<ContainerAllocator> const> ConstPtr;

}; // struct CartePosCustom_

typedef ::rm_msgs::CartePosCustom_<std::allocator<void> > CartePosCustom;

typedef boost::shared_ptr< ::rm_msgs::CartePosCustom > CartePosCustomPtr;
typedef boost::shared_ptr< ::rm_msgs::CartePosCustom const> CartePosCustomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::CartePosCustom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::CartePosCustom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::CartePosCustom_<ContainerAllocator1> & lhs, const ::rm_msgs::CartePosCustom_<ContainerAllocator2> & rhs)
{
  return lhs.Pose == rhs.Pose &&
    lhs.follow == rhs.follow &&
    lhs.trajectory_mode == rhs.trajectory_mode &&
    lhs.radio == rhs.radio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::CartePosCustom_<ContainerAllocator1> & lhs, const ::rm_msgs::CartePosCustom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::CartePosCustom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::CartePosCustom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::CartePosCustom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::CartePosCustom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::CartePosCustom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::CartePosCustom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::CartePosCustom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af7ee1edb545e20ac1d00c5aeafad8b0";
  }

  static const char* value(const ::rm_msgs::CartePosCustom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf7ee1edb545e20aULL;
  static const uint64_t static_value2 = 0xc1d00c5aeafad8b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::CartePosCustom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/CartePosCustom";
  }

  static const char* value(const ::rm_msgs::CartePosCustom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::CartePosCustom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose Pose\n"
"bool follow\n"
"uint8 trajectory_mode\n"
"uint8 radio\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rm_msgs::CartePosCustom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::CartePosCustom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Pose);
      stream.next(m.follow);
      stream.next(m.trajectory_mode);
      stream.next(m.radio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartePosCustom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::CartePosCustom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::CartePosCustom_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.Pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "follow: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.follow);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectory_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "radio: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_CARTEPOSCUSTOM_H
