// Generated by gencpp from file rm_msgs/Err.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ERR_H
#define RM_MSGS_MESSAGE_ERR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Err_
{
  typedef Err_<ContainerAllocator> Type;

  Err_()
    : err()  {
    }
  Err_(const ContainerAllocator& _alloc)
    : err(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _err_type;
  _err_type err;





  typedef boost::shared_ptr< ::rm_msgs::Err_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Err_<ContainerAllocator> const> ConstPtr;

}; // struct Err_

typedef ::rm_msgs::Err_<std::allocator<void> > Err;

typedef boost::shared_ptr< ::rm_msgs::Err > ErrPtr;
typedef boost::shared_ptr< ::rm_msgs::Err const> ErrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Err_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Err_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Err_<ContainerAllocator1> & lhs, const ::rm_msgs::Err_<ContainerAllocator2> & rhs)
{
  return lhs.err == rhs.err;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Err_<ContainerAllocator1> & lhs, const ::rm_msgs::Err_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Err_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Err_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Err_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Err_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Err_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Err_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Err_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b0a411346a36392edd94edb3ec31d40";
  }

  static const char* value(const ::rm_msgs::Err_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b0a411346a36392ULL;
  static const uint64_t static_value2 = 0xedd94edb3ec31d40ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Err_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Err";
  }

  static const char* value(const ::rm_msgs::Err_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Err_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] err\n"
;
  }

  static const char* value(const ::rm_msgs::Err_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Err_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.err);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Err_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Err_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Err_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "err: ";
    if (v.err.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.err.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.err[i]);
    }
    if (v.err.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_ERR_H
