// Generated by gencpp from file rm_msgs/Force_Position_Move_Pose_Custom.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_FORCE_POSITION_MOVE_POSE_CUSTOM_H
#define RM_MSGS_MESSAGE_FORCE_POSITION_MOVE_POSE_CUSTOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct Force_Position_Move_Pose_Custom_
{
  typedef Force_Position_Move_Pose_Custom_<ContainerAllocator> Type;

  Force_Position_Move_Pose_Custom_()
    : Pose()
    , sensor(0)
    , mode(0)
    , dir(0)
    , force(0)
    , follow(false)
    , trajectory_mode(0)
    , radio(0)  {
    }
  Force_Position_Move_Pose_Custom_(const ContainerAllocator& _alloc)
    : Pose(_alloc)
    , sensor(0)
    , mode(0)
    , dir(0)
    , force(0)
    , follow(false)
    , trajectory_mode(0)
    , radio(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _Pose_type;
  _Pose_type Pose;

   typedef uint8_t _sensor_type;
  _sensor_type sensor;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _dir_type;
  _dir_type dir;

   typedef int16_t _force_type;
  _force_type force;

   typedef uint8_t _follow_type;
  _follow_type follow;

   typedef uint8_t _trajectory_mode_type;
  _trajectory_mode_type trajectory_mode;

   typedef uint8_t _radio_type;
  _radio_type radio;





  typedef boost::shared_ptr< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> const> ConstPtr;

}; // struct Force_Position_Move_Pose_Custom_

typedef ::rm_msgs::Force_Position_Move_Pose_Custom_<std::allocator<void> > Force_Position_Move_Pose_Custom;

typedef boost::shared_ptr< ::rm_msgs::Force_Position_Move_Pose_Custom > Force_Position_Move_Pose_CustomPtr;
typedef boost::shared_ptr< ::rm_msgs::Force_Position_Move_Pose_Custom const> Force_Position_Move_Pose_CustomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator1> & lhs, const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator2> & rhs)
{
  return lhs.Pose == rhs.Pose &&
    lhs.sensor == rhs.sensor &&
    lhs.mode == rhs.mode &&
    lhs.dir == rhs.dir &&
    lhs.force == rhs.force &&
    lhs.follow == rhs.follow &&
    lhs.trajectory_mode == rhs.trajectory_mode &&
    lhs.radio == rhs.radio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator1> & lhs, const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba22909657b007c304f2b2ecbe12b041";
  }

  static const char* value(const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba22909657b007c3ULL;
  static const uint64_t static_value2 = 0x04f2b2ecbe12b041ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Force_Position_Move_Pose_Custom";
  }

  static const char* value(const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose Pose\n"
"uint8 sensor\n"
"uint8 mode\n"
"uint8 dir\n"
"int16 force\n"
"bool follow\n"
"uint8 trajectory_mode\n"
"uint8 radio\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Pose);
      stream.next(m.sensor);
      stream.next(m.mode);
      stream.next(m.dir);
      stream.next(m.force);
      stream.next(m.follow);
      stream.next(m.trajectory_mode);
      stream.next(m.radio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Force_Position_Move_Pose_Custom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Force_Position_Move_Pose_Custom_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.Pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dir);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "force: ";
    Printer<int16_t>::stream(s, indent + "  ", v.force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "follow: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.follow);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectory_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "radio: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_FORCE_POSITION_MOVE_POSE_CUSTOM_H
