// Generated by gencpp from file rm_msgs/Hand_Status.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_HAND_STATUS_H
#define RM_MSGS_MESSAGE_HAND_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Hand_Status_
{
  typedef Hand_Status_<ContainerAllocator> Type;

  Hand_Status_()
    : hand_angle()
    , hand_pos()
    , hand_state()
    , hand_force()
    , hand_err(0)  {
      hand_angle.assign(0);

      hand_pos.assign(0);

      hand_state.assign(0);

      hand_force.assign(0);
  }
  Hand_Status_(const ContainerAllocator& _alloc)
    : hand_angle()
    , hand_pos()
    , hand_state()
    , hand_force()
    , hand_err(0)  {
  (void)_alloc;
      hand_angle.assign(0);

      hand_pos.assign(0);

      hand_state.assign(0);

      hand_force.assign(0);
  }



   typedef boost::array<uint16_t, 6>  _hand_angle_type;
  _hand_angle_type hand_angle;

   typedef boost::array<uint16_t, 6>  _hand_pos_type;
  _hand_pos_type hand_pos;

   typedef boost::array<uint16_t, 6>  _hand_state_type;
  _hand_state_type hand_state;

   typedef boost::array<uint16_t, 6>  _hand_force_type;
  _hand_force_type hand_force;

   typedef uint16_t _hand_err_type;
  _hand_err_type hand_err;





  typedef boost::shared_ptr< ::rm_msgs::Hand_Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Hand_Status_<ContainerAllocator> const> ConstPtr;

}; // struct Hand_Status_

typedef ::rm_msgs::Hand_Status_<std::allocator<void> > Hand_Status;

typedef boost::shared_ptr< ::rm_msgs::Hand_Status > Hand_StatusPtr;
typedef boost::shared_ptr< ::rm_msgs::Hand_Status const> Hand_StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Hand_Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Hand_Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Hand_Status_<ContainerAllocator1> & lhs, const ::rm_msgs::Hand_Status_<ContainerAllocator2> & rhs)
{
  return lhs.hand_angle == rhs.hand_angle &&
    lhs.hand_pos == rhs.hand_pos &&
    lhs.hand_state == rhs.hand_state &&
    lhs.hand_force == rhs.hand_force &&
    lhs.hand_err == rhs.hand_err;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Hand_Status_<ContainerAllocator1> & lhs, const ::rm_msgs::Hand_Status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Hand_Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Hand_Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Hand_Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Hand_Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Hand_Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Hand_Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Hand_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cce752e69bf0b22631007e9bc8d2458";
  }

  static const char* value(const ::rm_msgs::Hand_Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cce752e69bf0b22ULL;
  static const uint64_t static_value2 = 0x631007e9bc8d2458ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Hand_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Hand_Status";
  }

  static const char* value(const ::rm_msgs::Hand_Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Hand_Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#灵巧手上报状态\n"
"\n"
"uint16[6] hand_angle	#手指角度数组，范围：0~2000.\n"
"uint16[6] hand_pos	#手指位置数组，范围：0~1000.\n"
"uint16[6] hand_state	#手指状态,0正在松开，1正在抓取，2位置到位停止，3力到位停止，5电流保护停止，6电缸堵转停止，7电缸故障停止\n"
"uint16[6] hand_force    #灵巧手自由度电流，单位mN\n"
"uint16  hand_err          #灵巧手系统错误，1表示有错误，0表示无错误\n"
;
  }

  static const char* value(const ::rm_msgs::Hand_Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Hand_Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hand_angle);
      stream.next(m.hand_pos);
      stream.next(m.hand_state);
      stream.next(m.hand_force);
      stream.next(m.hand_err);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hand_Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Hand_Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Hand_Status_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "hand_angle: ";
    if (v.hand_angle.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.hand_angle.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.hand_angle[i]);
    }
    if (v.hand_angle.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hand_pos: ";
    if (v.hand_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.hand_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.hand_pos[i]);
    }
    if (v.hand_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hand_state: ";
    if (v.hand_state.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.hand_state.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.hand_state[i]);
    }
    if (v.hand_state.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hand_force: ";
    if (v.hand_force.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.hand_force.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.hand_force[i]);
    }
    if (v.hand_force.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hand_err: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.hand_err);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_HAND_STATUS_H
