// Generated by gencpp from file rm_msgs/JointPosCustom.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_JOINTPOSCUSTOM_H
#define RM_MSGS_MESSAGE_JOINTPOSCUSTOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct JointPosCustom_
{
  typedef JointPosCustom_<ContainerAllocator> Type;

  JointPosCustom_()
    : joint()
    , expand(0.0)
    , follow(false)
    , trajectory_mode(0)
    , radio(0)  {
    }
  JointPosCustom_(const ContainerAllocator& _alloc)
    : joint(_alloc)
    , expand(0.0)
    , follow(false)
    , trajectory_mode(0)
    , radio(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_type;
  _joint_type joint;

   typedef float _expand_type;
  _expand_type expand;

   typedef uint8_t _follow_type;
  _follow_type follow;

   typedef uint8_t _trajectory_mode_type;
  _trajectory_mode_type trajectory_mode;

   typedef uint8_t _radio_type;
  _radio_type radio;





  typedef boost::shared_ptr< ::rm_msgs::JointPosCustom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::JointPosCustom_<ContainerAllocator> const> ConstPtr;

}; // struct JointPosCustom_

typedef ::rm_msgs::JointPosCustom_<std::allocator<void> > JointPosCustom;

typedef boost::shared_ptr< ::rm_msgs::JointPosCustom > JointPosCustomPtr;
typedef boost::shared_ptr< ::rm_msgs::JointPosCustom const> JointPosCustomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::JointPosCustom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::JointPosCustom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::JointPosCustom_<ContainerAllocator1> & lhs, const ::rm_msgs::JointPosCustom_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint &&
    lhs.expand == rhs.expand &&
    lhs.follow == rhs.follow &&
    lhs.trajectory_mode == rhs.trajectory_mode &&
    lhs.radio == rhs.radio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::JointPosCustom_<ContainerAllocator1> & lhs, const ::rm_msgs::JointPosCustom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::JointPosCustom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::JointPosCustom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::JointPosCustom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::JointPosCustom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::JointPosCustom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::JointPosCustom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::JointPosCustom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2953fc21da6104e47b8b6b70f74f1aee";
  }

  static const char* value(const ::rm_msgs::JointPosCustom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2953fc21da6104e4ULL;
  static const uint64_t static_value2 = 0x7b8b6b70f74f1aeeULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::JointPosCustom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/JointPosCustom";
  }

  static const char* value(const ::rm_msgs::JointPosCustom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::JointPosCustom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#control arm joints without planning\n"
"\n"
"float32[] joint\n"
"float32    expand\n"
"bool follow\n"
"uint8 trajectory_mode\n"
"uint8 radio\n"
;
  }

  static const char* value(const ::rm_msgs::JointPosCustom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::JointPosCustom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.expand);
      stream.next(m.follow);
      stream.next(m.trajectory_mode);
      stream.next(m.radio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPosCustom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::JointPosCustom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::JointPosCustom_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint: ";
    if (v.joint.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint[i]);
    }
    if (v.joint.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "expand: ";
    Printer<float>::stream(s, indent + "  ", v.expand);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "follow: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.follow);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectory_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "radio: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_JOINTPOSCUSTOM_H
