// Generated by gencpp from file rm_msgs/Joint_Speed.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_JOINT_SPEED_H
#define RM_MSGS_MESSAGE_JOINT_SPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Joint_Speed_
{
  typedef Joint_Speed_<ContainerAllocator> Type;

  Joint_Speed_()
    : joint_speed()  {
    }
  Joint_Speed_(const ContainerAllocator& _alloc)
    : joint_speed(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_speed_type;
  _joint_speed_type joint_speed;





  typedef boost::shared_ptr< ::rm_msgs::Joint_Speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Joint_Speed_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_Speed_

typedef ::rm_msgs::Joint_Speed_<std::allocator<void> > Joint_Speed;

typedef boost::shared_ptr< ::rm_msgs::Joint_Speed > Joint_SpeedPtr;
typedef boost::shared_ptr< ::rm_msgs::Joint_Speed const> Joint_SpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Joint_Speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Joint_Speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Joint_Speed_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_Speed_<ContainerAllocator2> & rhs)
{
  return lhs.joint_speed == rhs.joint_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Joint_Speed_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_Speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_Speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_Speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_Speed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_Speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_Speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Joint_Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33fe593b138a7242a779a630fd20122e";
  }

  static const char* value(const ::rm_msgs::Joint_Speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33fe593b138a7242ULL;
  static const uint64_t static_value2 = 0xa779a630fd20122eULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Joint_Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Joint_Speed";
  }

  static const char* value(const ::rm_msgs::Joint_Speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Joint_Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_speed\n"
;
  }

  static const char* value(const ::rm_msgs::Joint_Speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Joint_Speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_Speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Joint_Speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Joint_Speed_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_speed: ";
    if (v.joint_speed.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_speed.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint_speed[i]);
    }
    if (v.joint_speed.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_JOINT_SPEED_H
