// Generated by gencpp from file rm_msgs/Joint_Temperature.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_JOINT_TEMPERATURE_H
#define RM_MSGS_MESSAGE_JOINT_TEMPERATURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Joint_Temperature_
{
  typedef Joint_Temperature_<ContainerAllocator> Type;

  Joint_Temperature_()
    : joint_temperature()  {
    }
  Joint_Temperature_(const ContainerAllocator& _alloc)
    : joint_temperature(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_temperature_type;
  _joint_temperature_type joint_temperature;





  typedef boost::shared_ptr< ::rm_msgs::Joint_Temperature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Joint_Temperature_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_Temperature_

typedef ::rm_msgs::Joint_Temperature_<std::allocator<void> > Joint_Temperature;

typedef boost::shared_ptr< ::rm_msgs::Joint_Temperature > Joint_TemperaturePtr;
typedef boost::shared_ptr< ::rm_msgs::Joint_Temperature const> Joint_TemperatureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Joint_Temperature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Joint_Temperature_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_Temperature_<ContainerAllocator2> & rhs)
{
  return lhs.joint_temperature == rhs.joint_temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Joint_Temperature_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_Temperature_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_Temperature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_Temperature_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_Temperature_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7dbb3b0458bf6107a0e5950b28f68abf";
  }

  static const char* value(const ::rm_msgs::Joint_Temperature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7dbb3b0458bf6107ULL;
  static const uint64_t static_value2 = 0xa0e5950b28f68abfULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Joint_Temperature";
  }

  static const char* value(const ::rm_msgs::Joint_Temperature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_temperature\n"
;
  }

  static const char* value(const ::rm_msgs::Joint_Temperature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_Temperature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Joint_Temperature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Joint_Temperature_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_temperature: ";
    if (v.joint_temperature.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_temperature.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint_temperature[i]);
    }
    if (v.joint_temperature.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_JOINT_TEMPERATURE_H
