// Generated by gencpp from file rm_msgs/Joint_En_Flag.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_JOINT_EN_FLAG_H
#define RM_MSGS_MESSAGE_JOINT_EN_FLAG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Joint_En_Flag_
{
  typedef Joint_En_Flag_<ContainerAllocator> Type;

  Joint_En_Flag_()
    : joint_en_flag()  {
    }
  Joint_En_Flag_(const ContainerAllocator& _alloc)
    : joint_en_flag(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _joint_en_flag_type;
  _joint_en_flag_type joint_en_flag;





  typedef boost::shared_ptr< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_En_Flag_

typedef ::rm_msgs::Joint_En_Flag_<std::allocator<void> > Joint_En_Flag;

typedef boost::shared_ptr< ::rm_msgs::Joint_En_Flag > Joint_En_FlagPtr;
typedef boost::shared_ptr< ::rm_msgs::Joint_En_Flag const> Joint_En_FlagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Joint_En_Flag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Joint_En_Flag_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_En_Flag_<ContainerAllocator2> & rhs)
{
  return lhs.joint_en_flag == rhs.joint_en_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Joint_En_Flag_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_En_Flag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7e77bbef527559ebf285523745d1dc5";
  }

  static const char* value(const ::rm_msgs::Joint_En_Flag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7e77bbef527559eULL;
  static const uint64_t static_value2 = 0xbf285523745d1dc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Joint_En_Flag";
  }

  static const char* value(const ::rm_msgs::Joint_En_Flag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] joint_en_flag\n"
;
  }

  static const char* value(const ::rm_msgs::Joint_En_Flag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_en_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_En_Flag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Joint_En_Flag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Joint_En_Flag_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_en_flag: ";
    if (v.joint_en_flag.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_en_flag.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.joint_en_flag[i]);
    }
    if (v.joint_en_flag.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_JOINT_EN_FLAG_H
