// Generated by gencpp from file rm_msgs/Joint_Voltage.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_JOINT_VOLTAGE_H
#define RM_MSGS_MESSAGE_JOINT_VOLTAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Joint_Voltage_
{
  typedef Joint_Voltage_<ContainerAllocator> Type;

  Joint_Voltage_()
    : joint_voltage()  {
    }
  Joint_Voltage_(const ContainerAllocator& _alloc)
    : joint_voltage(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_voltage_type;
  _joint_voltage_type joint_voltage;





  typedef boost::shared_ptr< ::rm_msgs::Joint_Voltage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Joint_Voltage_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_Voltage_

typedef ::rm_msgs::Joint_Voltage_<std::allocator<void> > Joint_Voltage;

typedef boost::shared_ptr< ::rm_msgs::Joint_Voltage > Joint_VoltagePtr;
typedef boost::shared_ptr< ::rm_msgs::Joint_Voltage const> Joint_VoltageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Joint_Voltage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Joint_Voltage_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_Voltage_<ContainerAllocator2> & rhs)
{
  return lhs.joint_voltage == rhs.joint_voltage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Joint_Voltage_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_Voltage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_Voltage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_Voltage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_Voltage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f712751501e1263b5499f008c4b07694";
  }

  static const char* value(const ::rm_msgs::Joint_Voltage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf712751501e1263bULL;
  static const uint64_t static_value2 = 0x5499f008c4b07694ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Joint_Voltage";
  }

  static const char* value(const ::rm_msgs::Joint_Voltage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_voltage\n"
;
  }

  static const char* value(const ::rm_msgs::Joint_Voltage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_Voltage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Joint_Voltage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Joint_Voltage_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_voltage: ";
    if (v.joint_voltage.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_voltage.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint_voltage[i]);
    }
    if (v.joint_voltage.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_JOINT_VOLTAGE_H
