// Generated by gencpp from file rm_msgs/Joint_PoseEuler.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_JOINT_POSEEULER_H
#define RM_MSGS_MESSAGE_JOINT_POSEEULER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Joint_PoseEuler_
{
  typedef Joint_PoseEuler_<ContainerAllocator> Type;

  Joint_PoseEuler_()
    : euler()
    , position()  {
      euler.assign(0.0);

      position.assign(0.0);
  }
  Joint_PoseEuler_(const ContainerAllocator& _alloc)
    : euler()
    , position()  {
  (void)_alloc;
      euler.assign(0.0);

      position.assign(0.0);
  }



   typedef boost::array<float, 3>  _euler_type;
  _euler_type euler;

   typedef boost::array<float, 3>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> const> ConstPtr;

}; // struct Joint_PoseEuler_

typedef ::rm_msgs::Joint_PoseEuler_<std::allocator<void> > Joint_PoseEuler;

typedef boost::shared_ptr< ::rm_msgs::Joint_PoseEuler > Joint_PoseEulerPtr;
typedef boost::shared_ptr< ::rm_msgs::Joint_PoseEuler const> Joint_PoseEulerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator2> & rhs)
{
  return lhs.euler == rhs.euler &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator1> & lhs, const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9254815d452fb49553cab1a1384a3e0a";
  }

  static const char* value(const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9254815d452fb495ULL;
  static const uint64_t static_value2 = 0x53cab1a1384a3e0aULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Joint_PoseEuler";
  }

  static const char* value(const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] euler\n"
"float32[3] position\n"
;
  }

  static const char* value(const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.euler);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Joint_PoseEuler_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Joint_PoseEuler_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Joint_PoseEuler_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "euler: ";
    if (v.euler.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.euler.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.euler[i]);
    }
    if (v.euler.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    if (v.position.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.position[i]);
    }
    if (v.position.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_JOINT_POSEEULER_H
