// Generated by gencpp from file rm_msgs/Lift_In_Position.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_LIFT_IN_POSITION_H
#define RM_MSGS_MESSAGE_LIFT_IN_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Lift_In_Position_
{
  typedef Lift_In_Position_<ContainerAllocator> Type;

  Lift_In_Position_()
    : device(0)
    , state()
    , trajectory_connect(0)
    , trajectory_state(false)  {
    }
  Lift_In_Position_(const ContainerAllocator& _alloc)
    : device(0)
    , state(_alloc)
    , trajectory_connect(0)
    , trajectory_state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _device_type;
  _device_type device;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef uint8_t _trajectory_connect_type;
  _trajectory_connect_type trajectory_connect;

   typedef uint8_t _trajectory_state_type;
  _trajectory_state_type trajectory_state;





  typedef boost::shared_ptr< ::rm_msgs::Lift_In_Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Lift_In_Position_<ContainerAllocator> const> ConstPtr;

}; // struct Lift_In_Position_

typedef ::rm_msgs::Lift_In_Position_<std::allocator<void> > Lift_In_Position;

typedef boost::shared_ptr< ::rm_msgs::Lift_In_Position > Lift_In_PositionPtr;
typedef boost::shared_ptr< ::rm_msgs::Lift_In_Position const> Lift_In_PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Lift_In_Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Lift_In_Position_<ContainerAllocator1> & lhs, const ::rm_msgs::Lift_In_Position_<ContainerAllocator2> & rhs)
{
  return lhs.device == rhs.device &&
    lhs.state == rhs.state &&
    lhs.trajectory_connect == rhs.trajectory_connect &&
    lhs.trajectory_state == rhs.trajectory_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Lift_In_Position_<ContainerAllocator1> & lhs, const ::rm_msgs::Lift_In_Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Lift_In_Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Lift_In_Position_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Lift_In_Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8560798487e4b58bf325a3d3d0cad027";
  }

  static const char* value(const ::rm_msgs::Lift_In_Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8560798487e4b58bULL;
  static const uint64_t static_value2 = 0xf325a3d3d0cad027ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Lift_In_Position";
  }

  static const char* value(const ::rm_msgs::Lift_In_Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 device\n"
"string state\n"
"uint8 trajectory_connect\n"
"bool trajectory_state\n"
;
  }

  static const char* value(const ::rm_msgs::Lift_In_Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device);
      stream.next(m.state);
      stream.next(m.trajectory_connect);
      stream.next(m.trajectory_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lift_In_Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Lift_In_Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Lift_In_Position_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "device: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.device);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_connect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectory_connect);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trajectory_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_LIFT_IN_POSITION_H
