// Generated by gencpp from file rm_msgs/Read_Register.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_READ_REGISTER_H
#define RM_MSGS_MESSAGE_READ_REGISTER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Read_Register_
{
  typedef Read_Register_<ContainerAllocator> Type;

  Read_Register_()
    : port(0)
    , address(0)
    , num(0)
    , device(0)  {
    }
  Read_Register_(const ContainerAllocator& _alloc)
    : port(0)
    , address(0)
    , num(0)
    , device(0)  {
  (void)_alloc;
    }



   typedef uint8_t _port_type;
  _port_type port;

   typedef uint32_t _address_type;
  _address_type address;

   typedef uint32_t _num_type;
  _num_type num;

   typedef uint32_t _device_type;
  _device_type device;





  typedef boost::shared_ptr< ::rm_msgs::Read_Register_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Read_Register_<ContainerAllocator> const> ConstPtr;

}; // struct Read_Register_

typedef ::rm_msgs::Read_Register_<std::allocator<void> > Read_Register;

typedef boost::shared_ptr< ::rm_msgs::Read_Register > Read_RegisterPtr;
typedef boost::shared_ptr< ::rm_msgs::Read_Register const> Read_RegisterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Read_Register_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Read_Register_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Read_Register_<ContainerAllocator1> & lhs, const ::rm_msgs::Read_Register_<ContainerAllocator2> & rhs)
{
  return lhs.port == rhs.port &&
    lhs.address == rhs.address &&
    lhs.num == rhs.num &&
    lhs.device == rhs.device;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Read_Register_<ContainerAllocator1> & lhs, const ::rm_msgs::Read_Register_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Read_Register_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Read_Register_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Read_Register_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Read_Register_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Read_Register_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Read_Register_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Read_Register_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e80462a4b4637747ba287fa5251e9e0c";
  }

  static const char* value(const ::rm_msgs::Read_Register_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe80462a4b4637747ULL;
  static const uint64_t static_value2 = 0xba287fa5251e9e0cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Read_Register_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Read_Register";
  }

  static const char* value(const ::rm_msgs::Read_Register_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Read_Register_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 port\n"
"uint32 address\n"
"uint32 num\n"
"uint32 device\n"
;
  }

  static const char* value(const ::rm_msgs::Read_Register_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Read_Register_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port);
      stream.next(m.address);
      stream.next(m.num);
      stream.next(m.device);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Read_Register_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Read_Register_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Read_Register_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "port: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.port);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.device);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_READ_REGISTER_H
