// Generated by gencpp from file rm_msgs/Register_Data.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_REGISTER_DATA_H
#define RM_MSGS_MESSAGE_REGISTER_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Register_Data_
{
  typedef Register_Data_<ContainerAllocator> Type;

  Register_Data_()
    : data()
    , state(false)  {
    }
  Register_Data_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , state(false)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _data_type;
  _data_type data;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::rm_msgs::Register_Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Register_Data_<ContainerAllocator> const> ConstPtr;

}; // struct Register_Data_

typedef ::rm_msgs::Register_Data_<std::allocator<void> > Register_Data;

typedef boost::shared_ptr< ::rm_msgs::Register_Data > Register_DataPtr;
typedef boost::shared_ptr< ::rm_msgs::Register_Data const> Register_DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Register_Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Register_Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Register_Data_<ContainerAllocator1> & lhs, const ::rm_msgs::Register_Data_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Register_Data_<ContainerAllocator1> & lhs, const ::rm_msgs::Register_Data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Register_Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Register_Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Register_Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Register_Data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Register_Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Register_Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Register_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca800c21ed60db7e7472b2720ef8f45e";
  }

  static const char* value(const ::rm_msgs::Register_Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca800c21ed60db7eULL;
  static const uint64_t static_value2 = 0x7472b2720ef8f45eULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Register_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Register_Data";
  }

  static const char* value(const ::rm_msgs::Register_Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Register_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] data\n"
"bool state\n"
;
  }

  static const char* value(const ::rm_msgs::Register_Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Register_Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Register_Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Register_Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Register_Data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_REGISTER_DATA_H
