// Generated by gencpp from file rm_msgs/RS485_Mode.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RS485_MODE_H
#define RM_MSGS_MESSAGE_RS485_MODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RS485_Mode_
{
  typedef RS485_Mode_<ContainerAllocator> Type;

  RS485_Mode_()
    : controller_RS485_mode(0)
    , tool_RS485_mode(0)
    , baudrate(0)
    , modbus_timeout(0)  {
    }
  RS485_Mode_(const ContainerAllocator& _alloc)
    : controller_RS485_mode(0)
    , tool_RS485_mode(0)
    , baudrate(0)
    , modbus_timeout(0)  {
  (void)_alloc;
    }



   typedef uint8_t _controller_RS485_mode_type;
  _controller_RS485_mode_type controller_RS485_mode;

   typedef uint8_t _tool_RS485_mode_type;
  _tool_RS485_mode_type tool_RS485_mode;

   typedef uint32_t _baudrate_type;
  _baudrate_type baudrate;

   typedef uint32_t _modbus_timeout_type;
  _modbus_timeout_type modbus_timeout;





  typedef boost::shared_ptr< ::rm_msgs::RS485_Mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RS485_Mode_<ContainerAllocator> const> ConstPtr;

}; // struct RS485_Mode_

typedef ::rm_msgs::RS485_Mode_<std::allocator<void> > RS485_Mode;

typedef boost::shared_ptr< ::rm_msgs::RS485_Mode > RS485_ModePtr;
typedef boost::shared_ptr< ::rm_msgs::RS485_Mode const> RS485_ModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RS485_Mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RS485_Mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RS485_Mode_<ContainerAllocator1> & lhs, const ::rm_msgs::RS485_Mode_<ContainerAllocator2> & rhs)
{
  return lhs.controller_RS485_mode == rhs.controller_RS485_mode &&
    lhs.tool_RS485_mode == rhs.tool_RS485_mode &&
    lhs.baudrate == rhs.baudrate &&
    lhs.modbus_timeout == rhs.modbus_timeout;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RS485_Mode_<ContainerAllocator1> & lhs, const ::rm_msgs::RS485_Mode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RS485_Mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RS485_Mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RS485_Mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RS485_Mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RS485_Mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RS485_Mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RS485_Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68f472696d75d9d22a962adaba389926";
  }

  static const char* value(const ::rm_msgs::RS485_Mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68f472696d75d9d2ULL;
  static const uint64_t static_value2 = 0x2a962adaba389926ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RS485_Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RS485_Mode";
  }

  static const char* value(const ::rm_msgs::RS485_Mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RS485_Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 controller_RS485_mode\n"
"uint8 tool_RS485_mode\n"
"uint32 baudrate\n"
"uint32 modbus_timeout\n"
;
  }

  static const char* value(const ::rm_msgs::RS485_Mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RS485_Mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controller_RS485_mode);
      stream.next(m.tool_RS485_mode);
      stream.next(m.baudrate);
      stream.next(m.modbus_timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RS485_Mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RS485_Mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RS485_Mode_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "controller_RS485_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.controller_RS485_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tool_RS485_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tool_RS485_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "baudrate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.baudrate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "modbus_timeout: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.modbus_timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RS485_MODE_H
