// Generated by gencpp from file rm_msgs/Set_Realtime_Push.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SET_REALTIME_PUSH_H
#define RM_MSGS_MESSAGE_SET_REALTIME_PUSH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Set_Realtime_Push_
{
  typedef Set_Realtime_Push_<ContainerAllocator> Type;

  Set_Realtime_Push_()
    : cycle(0)
    , port(0)
    , force_coordinate(0)
    , ip()
    , aloha_state_enable(false)
    , arm_current_status_enable(false)
    , expand_state_enable(false)
    , hand_enable(false)
    , joint_acc_enable(false)
    , joint_speed_enable(false)
    , lift_state_enable(false)
    , tail_end_enable(false)
    , rm_plus_base_enable(false)
    , rm_plus_state_enable(false)  {
    }
  Set_Realtime_Push_(const ContainerAllocator& _alloc)
    : cycle(0)
    , port(0)
    , force_coordinate(0)
    , ip(_alloc)
    , aloha_state_enable(false)
    , arm_current_status_enable(false)
    , expand_state_enable(false)
    , hand_enable(false)
    , joint_acc_enable(false)
    , joint_speed_enable(false)
    , lift_state_enable(false)
    , tail_end_enable(false)
    , rm_plus_base_enable(false)
    , rm_plus_state_enable(false)  {
  (void)_alloc;
    }



   typedef uint16_t _cycle_type;
  _cycle_type cycle;

   typedef uint16_t _port_type;
  _port_type port;

   typedef uint16_t _force_coordinate_type;
  _force_coordinate_type force_coordinate;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ip_type;
  _ip_type ip;

   typedef uint8_t _aloha_state_enable_type;
  _aloha_state_enable_type aloha_state_enable;

   typedef uint8_t _arm_current_status_enable_type;
  _arm_current_status_enable_type arm_current_status_enable;

   typedef uint8_t _expand_state_enable_type;
  _expand_state_enable_type expand_state_enable;

   typedef uint8_t _hand_enable_type;
  _hand_enable_type hand_enable;

   typedef uint8_t _joint_acc_enable_type;
  _joint_acc_enable_type joint_acc_enable;

   typedef uint8_t _joint_speed_enable_type;
  _joint_speed_enable_type joint_speed_enable;

   typedef uint8_t _lift_state_enable_type;
  _lift_state_enable_type lift_state_enable;

   typedef uint8_t _tail_end_enable_type;
  _tail_end_enable_type tail_end_enable;

   typedef uint8_t _rm_plus_base_enable_type;
  _rm_plus_base_enable_type rm_plus_base_enable;

   typedef uint8_t _rm_plus_state_enable_type;
  _rm_plus_state_enable_type rm_plus_state_enable;





  typedef boost::shared_ptr< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> const> ConstPtr;

}; // struct Set_Realtime_Push_

typedef ::rm_msgs::Set_Realtime_Push_<std::allocator<void> > Set_Realtime_Push;

typedef boost::shared_ptr< ::rm_msgs::Set_Realtime_Push > Set_Realtime_PushPtr;
typedef boost::shared_ptr< ::rm_msgs::Set_Realtime_Push const> Set_Realtime_PushConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator1> & lhs, const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator2> & rhs)
{
  return lhs.cycle == rhs.cycle &&
    lhs.port == rhs.port &&
    lhs.force_coordinate == rhs.force_coordinate &&
    lhs.ip == rhs.ip &&
    lhs.aloha_state_enable == rhs.aloha_state_enable &&
    lhs.arm_current_status_enable == rhs.arm_current_status_enable &&
    lhs.expand_state_enable == rhs.expand_state_enable &&
    lhs.hand_enable == rhs.hand_enable &&
    lhs.joint_acc_enable == rhs.joint_acc_enable &&
    lhs.joint_speed_enable == rhs.joint_speed_enable &&
    lhs.lift_state_enable == rhs.lift_state_enable &&
    lhs.tail_end_enable == rhs.tail_end_enable &&
    lhs.rm_plus_base_enable == rhs.rm_plus_base_enable &&
    lhs.rm_plus_state_enable == rhs.rm_plus_state_enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator1> & lhs, const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29a80623aa411fb9cc6b96b119e8d448";
  }

  static const char* value(const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29a80623aa411fb9ULL;
  static const uint64_t static_value2 = 0xcc6b96b119e8d448ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Set_Realtime_Push";
  }

  static const char* value(const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 cycle\n"
"uint16 port\n"
"uint16 force_coordinate\n"
"string ip\n"
"bool aloha_state_enable\n"
"bool arm_current_status_enable\n"
"bool expand_state_enable\n"
"bool hand_enable\n"
"bool joint_acc_enable\n"
"bool joint_speed_enable\n"
"bool lift_state_enable\n"
"bool tail_end_enable\n"
"bool rm_plus_base_enable\n"
"bool rm_plus_state_enable\n"
;
  }

  static const char* value(const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cycle);
      stream.next(m.port);
      stream.next(m.force_coordinate);
      stream.next(m.ip);
      stream.next(m.aloha_state_enable);
      stream.next(m.arm_current_status_enable);
      stream.next(m.expand_state_enable);
      stream.next(m.hand_enable);
      stream.next(m.joint_acc_enable);
      stream.next(m.joint_speed_enable);
      stream.next(m.lift_state_enable);
      stream.next(m.tail_end_enable);
      stream.next(m.rm_plus_base_enable);
      stream.next(m.rm_plus_state_enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Set_Realtime_Push_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Set_Realtime_Push_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Set_Realtime_Push_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cycle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.cycle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "port: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.port);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "force_coordinate: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.force_coordinate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ip);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aloha_state_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aloha_state_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "arm_current_status_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm_current_status_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "expand_state_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.expand_state_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hand_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hand_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_acc_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joint_acc_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_speed_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joint_speed_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lift_state_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lift_state_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tail_end_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tail_end_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rm_plus_base_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rm_plus_base_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rm_plus_state_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rm_plus_state_enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_SET_REALTIME_PUSH_H
