// Generated by gencpp from file rm_msgs/Set_Modbus_Mode.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SET_MODBUS_MODE_H
#define RM_MSGS_MESSAGE_SET_MODBUS_MODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Set_Modbus_Mode_
{
  typedef Set_Modbus_Mode_<ContainerAllocator> Type;

  Set_Modbus_Mode_()
    : port(0)
    , baudrate(0)
    , timeout(0)
    , ip()  {
    }
  Set_Modbus_Mode_(const ContainerAllocator& _alloc)
    : port(0)
    , baudrate(0)
    , timeout(0)
    , ip(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _port_type;
  _port_type port;

   typedef uint32_t _baudrate_type;
  _baudrate_type baudrate;

   typedef uint32_t _timeout_type;
  _timeout_type timeout;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ip_type;
  _ip_type ip;





  typedef boost::shared_ptr< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> const> ConstPtr;

}; // struct Set_Modbus_Mode_

typedef ::rm_msgs::Set_Modbus_Mode_<std::allocator<void> > Set_Modbus_Mode;

typedef boost::shared_ptr< ::rm_msgs::Set_Modbus_Mode > Set_Modbus_ModePtr;
typedef boost::shared_ptr< ::rm_msgs::Set_Modbus_Mode const> Set_Modbus_ModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator1> & lhs, const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator2> & rhs)
{
  return lhs.port == rhs.port &&
    lhs.baudrate == rhs.baudrate &&
    lhs.timeout == rhs.timeout &&
    lhs.ip == rhs.ip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator1> & lhs, const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b976f7425d6e802fa67e71df2372ee55";
  }

  static const char* value(const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb976f7425d6e802fULL;
  static const uint64_t static_value2 = 0xa67e71df2372ee55ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Set_Modbus_Mode";
  }

  static const char* value(const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 port\n"
"uint32 baudrate\n"
"uint32 timeout\n"
"string ip\n"
;
  }

  static const char* value(const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port);
      stream.next(m.baudrate);
      stream.next(m.timeout);
      stream.next(m.ip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Set_Modbus_Mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Set_Modbus_Mode_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "port: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.port);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "baudrate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.baudrate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timeout: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timeout);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_SET_MODBUS_MODE_H
