// Generated by gencpp from file rm_msgs/Write_Register.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_WRITE_REGISTER_H
#define RM_MSGS_MESSAGE_WRITE_REGISTER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Write_Register_
{
  typedef Write_Register_<ContainerAllocator> Type;

  Write_Register_()
    : port(0)
    , address(0)
    , num(0)
    , data()
    , device(0)  {
    }
  Write_Register_(const ContainerAllocator& _alloc)
    : port(0)
    , address(0)
    , num(0)
    , data(_alloc)
    , device(0)  {
  (void)_alloc;
    }



   typedef uint8_t _port_type;
  _port_type port;

   typedef uint32_t _address_type;
  _address_type address;

   typedef uint32_t _num_type;
  _num_type num;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _data_type;
  _data_type data;

   typedef uint32_t _device_type;
  _device_type device;





  typedef boost::shared_ptr< ::rm_msgs::Write_Register_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Write_Register_<ContainerAllocator> const> ConstPtr;

}; // struct Write_Register_

typedef ::rm_msgs::Write_Register_<std::allocator<void> > Write_Register;

typedef boost::shared_ptr< ::rm_msgs::Write_Register > Write_RegisterPtr;
typedef boost::shared_ptr< ::rm_msgs::Write_Register const> Write_RegisterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Write_Register_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Write_Register_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Write_Register_<ContainerAllocator1> & lhs, const ::rm_msgs::Write_Register_<ContainerAllocator2> & rhs)
{
  return lhs.port == rhs.port &&
    lhs.address == rhs.address &&
    lhs.num == rhs.num &&
    lhs.data == rhs.data &&
    lhs.device == rhs.device;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Write_Register_<ContainerAllocator1> & lhs, const ::rm_msgs::Write_Register_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Write_Register_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Write_Register_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Write_Register_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Write_Register_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Write_Register_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Write_Register_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Write_Register_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f824a8509f33e365cbdaf7a07757719";
  }

  static const char* value(const ::rm_msgs::Write_Register_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f824a8509f33e36ULL;
  static const uint64_t static_value2 = 0x5cbdaf7a07757719ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Write_Register_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Write_Register";
  }

  static const char* value(const ::rm_msgs::Write_Register_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Write_Register_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 port\n"
"uint32 address\n"
"uint32 num\n"
"uint16[] data\n"
"uint32 device\n"
;
  }

  static const char* value(const ::rm_msgs::Write_Register_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Write_Register_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port);
      stream.next(m.address);
      stream.next(m.num);
      stream.next(m.data);
      stream.next(m.device);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Write_Register_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Write_Register_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Write_Register_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "port: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.port);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "address: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.address);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.device);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_WRITE_REGISTER_H
