# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Arm_Current_State.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Arm_Current_State(genpy.Message):
  _md5sum = "4c96583b56d85a30b9b36f7638260f04"
  _type = "rm_msgs/Arm_Current_State"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32[] joint
float32[6] Pose
uint16[] err
uint8 dof

"""
  __slots__ = ['joint','Pose','err','dof']
  _slot_types = ['float32[]','float32[6]','uint16[]','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joint,Pose,err,dof

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Arm_Current_State, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.joint is None:
        self.joint = []
      if self.Pose is None:
        self.Pose = [0.] * 6
      if self.err is None:
        self.err = []
      if self.dof is None:
        self.dof = 0
    else:
      self.joint = []
      self.Pose = [0.] * 6
      self.err = []
      self.dof = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.joint)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.joint))
      buff.write(_get_struct_6f().pack(*self.Pose))
      length = len(self.err)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(struct.Struct(pattern).pack(*self.err))
      _x = self.dof
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint = s.unpack(str[start:end])
      start = end
      end += 24
      self.Pose = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.err = s.unpack(str[start:end])
      start = end
      end += 1
      (self.dof,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.joint)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.joint.tostring())
      buff.write(self.Pose.tostring())
      length = len(self.err)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(self.err.tostring())
      _x = self.dof
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 24
      self.Pose = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=6)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.err = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=length)
      start = end
      end += 1
      (self.dof,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
