# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Hand_Status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Hand_Status(genpy.Message):
  _md5sum = "1cce752e69bf0b22631007e9bc8d2458"
  _type = "rm_msgs/Hand_Status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#灵巧手上报状态

uint16[6] hand_angle	#手指角度数组，范围：0~2000.
uint16[6] hand_pos	#手指位置数组，范围：0~1000.
uint16[6] hand_state	#手指状态,0正在松开，1正在抓取，2位置到位停止，3力到位停止，5电流保护停止，6电缸堵转停止，7电缸故障停止
uint16[6] hand_force    #灵巧手自由度电流，单位mN
uint16  hand_err          #灵巧手系统错误，1表示有错误，0表示无错误"""
  __slots__ = ['hand_angle','hand_pos','hand_state','hand_force','hand_err']
  _slot_types = ['uint16[6]','uint16[6]','uint16[6]','uint16[6]','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hand_angle,hand_pos,hand_state,hand_force,hand_err

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Hand_Status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hand_angle is None:
        self.hand_angle = [0] * 6
      if self.hand_pos is None:
        self.hand_pos = [0] * 6
      if self.hand_state is None:
        self.hand_state = [0] * 6
      if self.hand_force is None:
        self.hand_force = [0] * 6
      if self.hand_err is None:
        self.hand_err = 0
    else:
      self.hand_angle = [0] * 6
      self.hand_pos = [0] * 6
      self.hand_state = [0] * 6
      self.hand_force = [0] * 6
      self.hand_err = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_6H().pack(*self.hand_angle))
      buff.write(_get_struct_6H().pack(*self.hand_pos))
      buff.write(_get_struct_6H().pack(*self.hand_state))
      buff.write(_get_struct_6H().pack(*self.hand_force))
      _x = self.hand_err
      buff.write(_get_struct_H().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 12
      self.hand_angle = _get_struct_6H().unpack(str[start:end])
      start = end
      end += 12
      self.hand_pos = _get_struct_6H().unpack(str[start:end])
      start = end
      end += 12
      self.hand_state = _get_struct_6H().unpack(str[start:end])
      start = end
      end += 12
      self.hand_force = _get_struct_6H().unpack(str[start:end])
      start = end
      end += 2
      (self.hand_err,) = _get_struct_H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.hand_angle.tostring())
      buff.write(self.hand_pos.tostring())
      buff.write(self.hand_state.tostring())
      buff.write(self.hand_force.tostring())
      _x = self.hand_err
      buff.write(_get_struct_H().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 12
      self.hand_angle = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=6)
      start = end
      end += 12
      self.hand_pos = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=6)
      start = end
      end += 12
      self.hand_state = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=6)
      start = end
      end += 12
      self.hand_force = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=6)
      start = end
      end += 2
      (self.hand_err,) = _get_struct_H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6H = None
def _get_struct_6H():
    global _struct_6H
    if _struct_6H is None:
        _struct_6H = struct.Struct("<6H")
    return _struct_6H
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
