# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Rm_Plus_State.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Rm_Plus_State(genpy.Message):
  _md5sum = "decaf5adc4942742a6b89965c207ee54"
  _type = "rm_msgs/Rm_Plus_State"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 sys_state                 #系统状态
int32 sys_err                   #系统错误
int32[] dof_state               #各自由度当前状态
int32[] dof_err                 #各自由度错误信息
int32[] pos                     #各自由度当前位置
int32[] speed                   #各自由度当前速度
int32[] angle                   #各自由度当前角度
int32[] current                 #各自由度当前电流
int32[] normal_force            #自由度触觉三维力的法向力
int32[] tangential_force        #自由度触觉三维力的切向力
int32[] tangential_force_dir    #自由度触觉三维力的切向力方向
uint32[] tsa                    #自由度触觉自接近
uint32[] tma                    #自由度触觉互接近
int32[] touch_data              #触觉传感器原始数据
int32[] force                   #自由度力矩"""
  __slots__ = ['sys_state','sys_err','dof_state','dof_err','pos','speed','angle','current','normal_force','tangential_force','tangential_force_dir','tsa','tma','touch_data','force']
  _slot_types = ['int32','int32','int32[]','int32[]','int32[]','int32[]','int32[]','int32[]','int32[]','int32[]','int32[]','uint32[]','uint32[]','int32[]','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sys_state,sys_err,dof_state,dof_err,pos,speed,angle,current,normal_force,tangential_force,tangential_force_dir,tsa,tma,touch_data,force

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Rm_Plus_State, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sys_state is None:
        self.sys_state = 0
      if self.sys_err is None:
        self.sys_err = 0
      if self.dof_state is None:
        self.dof_state = []
      if self.dof_err is None:
        self.dof_err = []
      if self.pos is None:
        self.pos = []
      if self.speed is None:
        self.speed = []
      if self.angle is None:
        self.angle = []
      if self.current is None:
        self.current = []
      if self.normal_force is None:
        self.normal_force = []
      if self.tangential_force is None:
        self.tangential_force = []
      if self.tangential_force_dir is None:
        self.tangential_force_dir = []
      if self.tsa is None:
        self.tsa = []
      if self.tma is None:
        self.tma = []
      if self.touch_data is None:
        self.touch_data = []
      if self.force is None:
        self.force = []
    else:
      self.sys_state = 0
      self.sys_err = 0
      self.dof_state = []
      self.dof_err = []
      self.pos = []
      self.speed = []
      self.angle = []
      self.current = []
      self.normal_force = []
      self.tangential_force = []
      self.tangential_force_dir = []
      self.tsa = []
      self.tma = []
      self.touch_data = []
      self.force = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i().pack(_x.sys_state, _x.sys_err))
      length = len(self.dof_state)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.dof_state))
      length = len(self.dof_err)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.dof_err))
      length = len(self.pos)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.pos))
      length = len(self.speed)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.speed))
      length = len(self.angle)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.angle))
      length = len(self.current)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.current))
      length = len(self.normal_force)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.normal_force))
      length = len(self.tangential_force)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.tangential_force))
      length = len(self.tangential_force_dir)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.tangential_force_dir))
      length = len(self.tsa)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.tsa))
      length = len(self.tma)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.tma))
      length = len(self.touch_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.touch_data))
      length = len(self.force)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.force))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.sys_state, _x.sys_err,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dof_state = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dof_err = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pos = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.speed = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.angle = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.current = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.normal_force = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tangential_force = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tangential_force_dir = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tsa = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tma = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.touch_data = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.force = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i().pack(_x.sys_state, _x.sys_err))
      length = len(self.dof_state)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.dof_state.tostring())
      length = len(self.dof_err)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.dof_err.tostring())
      length = len(self.pos)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.pos.tostring())
      length = len(self.speed)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.speed.tostring())
      length = len(self.angle)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.angle.tostring())
      length = len(self.current)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.current.tostring())
      length = len(self.normal_force)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.normal_force.tostring())
      length = len(self.tangential_force)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.tangential_force.tostring())
      length = len(self.tangential_force_dir)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.tangential_force_dir.tostring())
      length = len(self.tsa)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.tsa.tostring())
      length = len(self.tma)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.tma.tostring())
      length = len(self.touch_data)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.touch_data.tostring())
      length = len(self.force)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.force.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.sys_state, _x.sys_err,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dof_state = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.dof_err = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pos = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.speed = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.angle = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.current = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.normal_force = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tangential_force = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tangential_force_dir = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tsa = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tma = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.touch_data = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.force = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
