# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Rm_Plus_Base.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Rm_Plus_Base(genpy.Message):
  _md5sum = "6811b6d3be27919dd94cf28267ef3a90"
  _type = "rm_msgs/Rm_Plus_Base"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string manu              # 设备厂家
int8 type                # 设备类型 1：两指夹爪 2：五指灵巧手 3：三指夹爪
string hv                # 硬件版本
string sv                # 软件版本
string bv                # boot版本
int32 id                 # 设备ID
int8 dof                 # 自由度
int8 check               # 自检开关
int8 bee                 # 蜂鸣器开关
bool force               # 力控支持
bool touch               # 触觉支持
int8 touch_num           # 触觉个数
int8 touch_sw            # 触觉开关
int8 hand                # 手方向 1 ：左手 2： 右手
int32[] pos_up           # 位置上限,单位：无量纲
int32[] pos_low          # 位置下限,单位：无量纲
int32[] angle_up         # 角度上限,单位：0.01度
int32[] angle_low        # 角度下限,单位：0.01度
int32[] speed_up         # 速度上限,单位：无量纲
int32[] speed_low        # 速度下限,单位：无量纲
int32[] force_up         # 力上限,单位：0.001N 
int32[] force_low        # 力下限,单位：0.001N 
"""
  __slots__ = ['manu','type','hv','sv','bv','id','dof','check','bee','force','touch','touch_num','touch_sw','hand','pos_up','pos_low','angle_up','angle_low','speed_up','speed_low','force_up','force_low']
  _slot_types = ['string','int8','string','string','string','int32','int8','int8','int8','bool','bool','int8','int8','int8','int32[]','int32[]','int32[]','int32[]','int32[]','int32[]','int32[]','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       manu,type,hv,sv,bv,id,dof,check,bee,force,touch,touch_num,touch_sw,hand,pos_up,pos_low,angle_up,angle_low,speed_up,speed_low,force_up,force_low

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Rm_Plus_Base, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.manu is None:
        self.manu = ''
      if self.type is None:
        self.type = 0
      if self.hv is None:
        self.hv = ''
      if self.sv is None:
        self.sv = ''
      if self.bv is None:
        self.bv = ''
      if self.id is None:
        self.id = 0
      if self.dof is None:
        self.dof = 0
      if self.check is None:
        self.check = 0
      if self.bee is None:
        self.bee = 0
      if self.force is None:
        self.force = False
      if self.touch is None:
        self.touch = False
      if self.touch_num is None:
        self.touch_num = 0
      if self.touch_sw is None:
        self.touch_sw = 0
      if self.hand is None:
        self.hand = 0
      if self.pos_up is None:
        self.pos_up = []
      if self.pos_low is None:
        self.pos_low = []
      if self.angle_up is None:
        self.angle_up = []
      if self.angle_low is None:
        self.angle_low = []
      if self.speed_up is None:
        self.speed_up = []
      if self.speed_low is None:
        self.speed_low = []
      if self.force_up is None:
        self.force_up = []
      if self.force_low is None:
        self.force_low = []
    else:
      self.manu = ''
      self.type = 0
      self.hv = ''
      self.sv = ''
      self.bv = ''
      self.id = 0
      self.dof = 0
      self.check = 0
      self.bee = 0
      self.force = False
      self.touch = False
      self.touch_num = 0
      self.touch_sw = 0
      self.hand = 0
      self.pos_up = []
      self.pos_low = []
      self.angle_up = []
      self.angle_low = []
      self.speed_up = []
      self.speed_low = []
      self.force_up = []
      self.force_low = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.manu
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.type
      buff.write(_get_struct_b().pack(_x))
      _x = self.hv
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.sv
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.bv
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i3b2B3b().pack(_x.id, _x.dof, _x.check, _x.bee, _x.force, _x.touch, _x.touch_num, _x.touch_sw, _x.hand))
      length = len(self.pos_up)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.pos_up))
      length = len(self.pos_low)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.pos_low))
      length = len(self.angle_up)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.angle_up))
      length = len(self.angle_low)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.angle_low))
      length = len(self.speed_up)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.speed_up))
      length = len(self.speed_low)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.speed_low))
      length = len(self.force_up)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.force_up))
      length = len(self.force_low)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.force_low))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.manu = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.manu = str[start:end]
      start = end
      end += 1
      (self.type,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.hv = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.hv = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sv = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sv = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bv = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.bv = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.id, _x.dof, _x.check, _x.bee, _x.force, _x.touch, _x.touch_num, _x.touch_sw, _x.hand,) = _get_struct_i3b2B3b().unpack(str[start:end])
      self.force = bool(self.force)
      self.touch = bool(self.touch)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pos_up = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pos_low = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.angle_up = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.angle_low = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.speed_up = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.speed_low = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.force_up = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.force_low = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.manu
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.type
      buff.write(_get_struct_b().pack(_x))
      _x = self.hv
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.sv
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.bv
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i3b2B3b().pack(_x.id, _x.dof, _x.check, _x.bee, _x.force, _x.touch, _x.touch_num, _x.touch_sw, _x.hand))
      length = len(self.pos_up)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.pos_up.tostring())
      length = len(self.pos_low)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.pos_low.tostring())
      length = len(self.angle_up)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.angle_up.tostring())
      length = len(self.angle_low)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.angle_low.tostring())
      length = len(self.speed_up)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.speed_up.tostring())
      length = len(self.speed_low)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.speed_low.tostring())
      length = len(self.force_up)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.force_up.tostring())
      length = len(self.force_low)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.force_low.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.manu = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.manu = str[start:end]
      start = end
      end += 1
      (self.type,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.hv = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.hv = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sv = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sv = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.bv = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.bv = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.id, _x.dof, _x.check, _x.bee, _x.force, _x.touch, _x.touch_num, _x.touch_sw, _x.hand,) = _get_struct_i3b2B3b().unpack(str[start:end])
      self.force = bool(self.force)
      self.touch = bool(self.touch)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pos_up = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pos_low = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.angle_up = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.angle_low = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.speed_up = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.speed_low = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.force_up = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.force_low = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
_struct_i3b2B3b = None
def _get_struct_i3b2B3b():
    global _struct_i3b2B3b
    if _struct_i3b2B3b is None:
        _struct_i3b2B3b = struct.Struct("<i3b2B3b")
    return _struct_i3b2B3b
