# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RS485_Mode.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RS485_Mode(genpy.Message):
  _md5sum = "68f472696d75d9d22a962adaba389926"
  _type = "rm_msgs/RS485_Mode"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 controller_RS485_mode
uint8 tool_RS485_mode
uint32 baudrate
uint32 modbus_timeout"""
  __slots__ = ['controller_RS485_mode','tool_RS485_mode','baudrate','modbus_timeout']
  _slot_types = ['uint8','uint8','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       controller_RS485_mode,tool_RS485_mode,baudrate,modbus_timeout

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RS485_Mode, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.controller_RS485_mode is None:
        self.controller_RS485_mode = 0
      if self.tool_RS485_mode is None:
        self.tool_RS485_mode = 0
      if self.baudrate is None:
        self.baudrate = 0
      if self.modbus_timeout is None:
        self.modbus_timeout = 0
    else:
      self.controller_RS485_mode = 0
      self.tool_RS485_mode = 0
      self.baudrate = 0
      self.modbus_timeout = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2I().pack(_x.controller_RS485_mode, _x.tool_RS485_mode, _x.baudrate, _x.modbus_timeout))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.controller_RS485_mode, _x.tool_RS485_mode, _x.baudrate, _x.modbus_timeout,) = _get_struct_2B2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2I().pack(_x.controller_RS485_mode, _x.tool_RS485_mode, _x.baudrate, _x.modbus_timeout))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.controller_RS485_mode, _x.tool_RS485_mode, _x.baudrate, _x.modbus_timeout,) = _get_struct_2B2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2I = None
def _get_struct_2B2I():
    global _struct_2B2I
    if _struct_2B2I is None:
        _struct_2B2I = struct.Struct("<2B2I")
    return _struct_2B2I
