# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Set_Realtime_Push.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Set_Realtime_Push(genpy.Message):
  _md5sum = "29a80623aa411fb9cc6b96b119e8d448"
  _type = "rm_msgs/Set_Realtime_Push"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 cycle
uint16 port
uint16 force_coordinate
string ip
bool aloha_state_enable
bool arm_current_status_enable
bool expand_state_enable
bool hand_enable
bool joint_acc_enable
bool joint_speed_enable
bool lift_state_enable
bool tail_end_enable
bool rm_plus_base_enable
bool rm_plus_state_enable"""
  __slots__ = ['cycle','port','force_coordinate','ip','aloha_state_enable','arm_current_status_enable','expand_state_enable','hand_enable','joint_acc_enable','joint_speed_enable','lift_state_enable','tail_end_enable','rm_plus_base_enable','rm_plus_state_enable']
  _slot_types = ['uint16','uint16','uint16','string','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cycle,port,force_coordinate,ip,aloha_state_enable,arm_current_status_enable,expand_state_enable,hand_enable,joint_acc_enable,joint_speed_enable,lift_state_enable,tail_end_enable,rm_plus_base_enable,rm_plus_state_enable

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Set_Realtime_Push, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cycle is None:
        self.cycle = 0
      if self.port is None:
        self.port = 0
      if self.force_coordinate is None:
        self.force_coordinate = 0
      if self.ip is None:
        self.ip = ''
      if self.aloha_state_enable is None:
        self.aloha_state_enable = False
      if self.arm_current_status_enable is None:
        self.arm_current_status_enable = False
      if self.expand_state_enable is None:
        self.expand_state_enable = False
      if self.hand_enable is None:
        self.hand_enable = False
      if self.joint_acc_enable is None:
        self.joint_acc_enable = False
      if self.joint_speed_enable is None:
        self.joint_speed_enable = False
      if self.lift_state_enable is None:
        self.lift_state_enable = False
      if self.tail_end_enable is None:
        self.tail_end_enable = False
      if self.rm_plus_base_enable is None:
        self.rm_plus_base_enable = False
      if self.rm_plus_state_enable is None:
        self.rm_plus_state_enable = False
    else:
      self.cycle = 0
      self.port = 0
      self.force_coordinate = 0
      self.ip = ''
      self.aloha_state_enable = False
      self.arm_current_status_enable = False
      self.expand_state_enable = False
      self.hand_enable = False
      self.joint_acc_enable = False
      self.joint_speed_enable = False
      self.lift_state_enable = False
      self.tail_end_enable = False
      self.rm_plus_base_enable = False
      self.rm_plus_state_enable = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3H().pack(_x.cycle, _x.port, _x.force_coordinate))
      _x = self.ip
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10B().pack(_x.aloha_state_enable, _x.arm_current_status_enable, _x.expand_state_enable, _x.hand_enable, _x.joint_acc_enable, _x.joint_speed_enable, _x.lift_state_enable, _x.tail_end_enable, _x.rm_plus_base_enable, _x.rm_plus_state_enable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.cycle, _x.port, _x.force_coordinate,) = _get_struct_3H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ip = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ip = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.aloha_state_enable, _x.arm_current_status_enable, _x.expand_state_enable, _x.hand_enable, _x.joint_acc_enable, _x.joint_speed_enable, _x.lift_state_enable, _x.tail_end_enable, _x.rm_plus_base_enable, _x.rm_plus_state_enable,) = _get_struct_10B().unpack(str[start:end])
      self.aloha_state_enable = bool(self.aloha_state_enable)
      self.arm_current_status_enable = bool(self.arm_current_status_enable)
      self.expand_state_enable = bool(self.expand_state_enable)
      self.hand_enable = bool(self.hand_enable)
      self.joint_acc_enable = bool(self.joint_acc_enable)
      self.joint_speed_enable = bool(self.joint_speed_enable)
      self.lift_state_enable = bool(self.lift_state_enable)
      self.tail_end_enable = bool(self.tail_end_enable)
      self.rm_plus_base_enable = bool(self.rm_plus_base_enable)
      self.rm_plus_state_enable = bool(self.rm_plus_state_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3H().pack(_x.cycle, _x.port, _x.force_coordinate))
      _x = self.ip
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10B().pack(_x.aloha_state_enable, _x.arm_current_status_enable, _x.expand_state_enable, _x.hand_enable, _x.joint_acc_enable, _x.joint_speed_enable, _x.lift_state_enable, _x.tail_end_enable, _x.rm_plus_base_enable, _x.rm_plus_state_enable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.cycle, _x.port, _x.force_coordinate,) = _get_struct_3H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ip = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ip = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.aloha_state_enable, _x.arm_current_status_enable, _x.expand_state_enable, _x.hand_enable, _x.joint_acc_enable, _x.joint_speed_enable, _x.lift_state_enable, _x.tail_end_enable, _x.rm_plus_base_enable, _x.rm_plus_state_enable,) = _get_struct_10B().unpack(str[start:end])
      self.aloha_state_enable = bool(self.aloha_state_enable)
      self.arm_current_status_enable = bool(self.arm_current_status_enable)
      self.expand_state_enable = bool(self.expand_state_enable)
      self.hand_enable = bool(self.hand_enable)
      self.joint_acc_enable = bool(self.joint_acc_enable)
      self.joint_speed_enable = bool(self.joint_speed_enable)
      self.lift_state_enable = bool(self.lift_state_enable)
      self.tail_end_enable = bool(self.tail_end_enable)
      self.rm_plus_base_enable = bool(self.rm_plus_base_enable)
      self.rm_plus_state_enable = bool(self.rm_plus_state_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10B = None
def _get_struct_10B():
    global _struct_10B
    if _struct_10B is None:
        _struct_10B = struct.Struct("<10B")
    return _struct_10B
_struct_3H = None
def _get_struct_3H():
    global _struct_3H
    if _struct_3H is None:
        _struct_3H = struct.Struct("<3H")
    return _struct_3H
