// Generated by gencpp from file pose_estimation_pkg/Pose6D.msg
// DO NOT EDIT!


#ifndef POSE_ESTIMATION_PKG_MESSAGE_POSE6D_H
#define POSE_ESTIMATION_PKG_MESSAGE_POSE6D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pose_estimation_pkg
{
template <class ContainerAllocator>
struct Pose6D_
{
  typedef Pose6D_<ContainerAllocator> Type;

  Pose6D_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rx(0.0)
    , ry(0.0)
    , rz(0.0)  {
    }
  Pose6D_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rx(0.0)
    , ry(0.0)
    , rz(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _rx_type;
  _rx_type rx;

   typedef double _ry_type;
  _ry_type ry;

   typedef double _rz_type;
  _rz_type rz;





  typedef boost::shared_ptr< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> const> ConstPtr;

}; // struct Pose6D_

typedef ::pose_estimation_pkg::Pose6D_<std::allocator<void> > Pose6D;

typedef boost::shared_ptr< ::pose_estimation_pkg::Pose6D > Pose6DPtr;
typedef boost::shared_ptr< ::pose_estimation_pkg::Pose6D const> Pose6DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_estimation_pkg::Pose6D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_estimation_pkg::Pose6D_<ContainerAllocator1> & lhs, const ::pose_estimation_pkg::Pose6D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.rx == rhs.rx &&
    lhs.ry == rhs.ry &&
    lhs.rz == rhs.rz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_estimation_pkg::Pose6D_<ContainerAllocator1> & lhs, const ::pose_estimation_pkg::Pose6D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_estimation_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88d995302418aa13534aa14fc9aeed94";
  }

  static const char* value(const ::pose_estimation_pkg::Pose6D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88d995302418aa13ULL;
  static const uint64_t static_value2 = 0x534aa14fc9aeed94ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_estimation_pkg/Pose6D";
  }

  static const char* value(const ::pose_estimation_pkg::Pose6D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 rx   \n"
"float64 ry\n"
"float64 rz\n"
;
  }

  static const char* value(const ::pose_estimation_pkg::Pose6D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rx);
      stream.next(m.ry);
      stream.next(m.rz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose6D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_estimation_pkg::Pose6D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_estimation_pkg::Pose6D_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rx: ";
    Printer<double>::stream(s, indent + "  ", v.rx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ry: ";
    Printer<double>::stream(s, indent + "  ", v.ry);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rz: ";
    Printer<double>::stream(s, indent + "  ", v.rz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_ESTIMATION_PKG_MESSAGE_POSE6D_H
