(cl:in-package rm_msgs-msg)
(cl:export '(SYS_STATE-VAL
          SYS_STATE
          SYS_ERR-VAL
          SYS_ERR
          DOF_STATE-VAL
          DOF_STATE
          DOF_ERR-VAL
          DOF_ERR
          POS-VAL
          POS
          SPEED-VAL
          SPEED
          ANGLE-VAL
          ANGLE
          CURRENT-VAL
          CURRENT
          NORMAL_FORCE-VAL
          NORMAL_FORCE
          TANGENTIAL_FORCE-VAL
          TANGENTIAL_FORCE
          TANGENTIAL_FORCE_DIR-VAL
          TANGENTIAL_FORCE_DIR
          TSA-VAL
          TSA
          TMA-VAL
          TMA
          TOUCH_DATA-VAL
          TOUCH_DATA
          FORCE-VAL
          FORCE
))