(cl:in-package rm_msgs-msg)
(cl:export '(MANU-VAL
          MANU
          TYPE-VAL
          TYPE
          HV-VAL
          HV
          SV-VAL
          SV
          BV-VAL
          BV
          ID-VAL
          ID
          DOF-VAL
          DOF
          CHECK-VAL
          CHECK
          BEE-VAL
          BEE
          FORCE-VAL
          FORCE
          TOUCH-VAL
          TOUCH
          TOUCH_NUM-VAL
          TOUCH_NUM
          TOUCH_SW-VAL
          TOUCH_SW
          HAND-VAL
          HAND
          POS_UP-VAL
          POS_UP
          POS_LOW-VAL
          POS_LOW
          ANGLE_UP-VAL
          ANGLE_UP
          ANGLE_LOW-VAL
          ANGLE_LOW
          SPEED_UP-VAL
          SPEED_UP
          SPEED_LOW-VAL
          SPEED_LOW
          FORCE_UP-VAL
          FORCE_UP
          FORCE_LOW-VAL
          FORCE_LOW
))